[Issue: 1291] Update cd-* scripts to deploy staging
HHS/simpler-grants-gov pull request #1821
Opened 2024-04-24 14:44 UTC by aplybeah

## Summary
Fixes #1291

### Time to review: __1 min__

## Changes proposed
* add `staging` input to `cd-api` and `cd-frontend` files

## Context for reviewers
> The cd files need to be configured to also deploy the staging environment

## Additional information
N/A

2024-04-24 17:09 UTC, chouinar submitted a review, later dismissed

2024-04-24 17:19 UTC, coilysiren requested changes

2024-04-24 17:19 UTC, coilysiren commented on .github/workflows/cd-frontend.yml
> +          - staging
Unfortunately adding `staging` here won't change much. It just makes staging available as an option, but doesn't actually start deploying staging. The line you want to change is down below...

2024-04-24 17:19 UTC, coilysiren commented on .github/workflows/cd-frontend.yml
...the line you want to change is this one down below

```
environment: ${{ inputs.environment || (github.event_name == 'release' && 'prod') || 'dev' }}
```

change it to (psuedo-code)

```
environment: ${{ inputs.environment || (github.event_name == 'release' && 'prod') || ['dev', 'staging'] }}
```

2024-04-24 17:19 UTC, coilysiren commented on .github/workflows/cd-frontend.yml
You'll need to do this for the analytics package as well, of course.

2024-04-24 17:34 UTC, coilysiren commented on .github/workflows/cd-frontend.yml
>          type: choice
You'll need to change `run-name:` above as well

2024-04-29 16:26 UTC, coilysiren approved these changes
This looks right 👍🏼 I would just recommend testing it before merging

2024-04-30 21:18 UTC, merged