Round Sprinty McBurndown's output to integers
HHS/simpler-grants-gov pull request #1976
Opened 2024-05-09 17:43 UTC by AlexanderStephensonUSDS

## Summary
Fixes #1850 

### Time to review: 2 minutes

## Changes proposed

Adds code to metrics to covert float percentages to whole integers.

## Context for reviewers
> Testing instructions, background context, more in-depth details of the implementation, and anything else you'd like to call out or ask reviewers. Explain how the changes were verified.

## Additional information

See Screenshot from local CLI.
![burndown](https://github.com/HHS/simpler-grants-gov/assets/134650917/11274c67-983a-43a3-a3dc-f35e2d4a684c)
![burnup](https://github.com/HHS/simpler-grants-gov/assets/134650917/b6cb033d-9e55-47ff-966d-7e2f0c0cbfc9)
![percent_deliver](https://github.com/HHS/simpler-grants-gov/assets/134650917/2bdd9d82-97e6-4e58-a88f-f7dbea4be8a9)

2024-05-09 17:54 UTC, coilysiren commented
@AlexanderStephensonUSDS let me know if you need help with the CI failures

2024-05-09 17:57 UTC, AlexanderStephensonUSDS commented
@coilysiren What do I need to fix for the Anchore Scan vulnerability check failure?

2024-05-09 18:03 UTC, coilysiren commented
@AlexanderStephensonUSDS if you look at the check, you'll see this

<img width="597" alt="image" src="https://github.com/HHS/simpler-grants-gov/assets/5768468/0158d8d0-6e0f-49fe-be6f-2091547395e5">

It's referencing the current version of `Jinja2`, which is being installed here: https://github.com/HHS/simpler-grants-gov/blob/779201c4c6c5d95a81cd60245d1103d785629c3f/analytics/poetry.lock#L899-L900

To fix the scan, you need to update `Jinja2`. You can do that with the following command:

```bash
$ poetry update
```

2024-05-09 18:09 UTC, coilysiren submitted a review, later dismissed

2024-05-10 15:48 UTC, widal001 requested changes
Hey @AlexanderStephensonUSDS thanks for finding and making these changes in the necessary places!

One small edit (which I should have made more clear in the ticket) we want to round the numbers to the nearest whole percentage point rather than simply flooring them to their integer value.

I left a few code suggestions that you should be able to accept, but can you update the other uses of `int()` alone as well?

2024-05-10 15:48 UTC, widal001 commented on analytics/src/analytics/metrics/burndown.py
> +        pct_closed = int(total_closed / total_opened * 100)
I think we might actually want this: 
```suggestion
        pct_closed = int(round(total_closed / total_opened * 100, 0))
```

`int()` by itself just floors a float and we want to round to the nearest whole number

2024-05-10 15:48 UTC, widal001 commented on analytics/tests/metrics/test_burndown.py
> +        assert output.stats.get(self.PCT_CLOSED).value == 66  # rounded to 2 places
```suggestion
        assert output.stats.get(self.PCT_CLOSED).value == 67  # rounded to nearest whole number
```

Changed this sounds it reflects the rounding to the nearest whole number

2024-05-10 23:04 UTC, AlexanderStephensonUSDS commented
Yes. Makes sense.

Will make the requested changes.

On May 10, 2024, at 10:49 AM, Billy Daly ***@***.***> wrote:

﻿

@widal001 requested changes on this pull request.

Hey @AlexanderStephensonUSDS<https://github.com/AlexanderStephensonUSDS> thanks for finding and making these changes in the necessary places!

One small edit (which I should have made more clear in the ticket) we want to round the numbers to the nearest whole percentage point rather than simply flooring them to their integer value.

I left a few code suggestions that you should be able to accept, but can you update the other uses of int() alone as well?

________________________________

In analytics/src/analytics/metrics/burndown.py<https://github.com/HHS/simpler-grants-gov/pull/1976#discussion_r1596916888>:

> @@ -105,12 +105,12 @@ def get_stats(self) -> dict[str, Statistic]:
         # get open and closed counts and percentages
         total_opened = int(df["opened"].sum())
         total_closed = int(df["closed"].sum())
-        pct_closed = round(total_closed / total_opened * 100, 2)
+        pct_closed = int(total_closed / total_opened * 100)


I think we might actually want this:

⬇️ Suggested change

-        pct_closed = int(total_closed / total_opened * 100)
+        pct_closed = int(round(total_closed / total_opened * 100, 0))


int() by itself just floors a float and we want to round to the nearest whole number

________________________________

In analytics/tests/metrics/test_burndown.py<https://github.com/HHS/simpler-grants-gov/pull/1976#discussion_r1596919569>:

> @@ -356,7 +356,7 @@ def test_include_issues_closed_after_sprint_end(self):
         # validation
         assert output.stats.get(self.TOTAL_CLOSED).value == 2
         assert output.stats.get(self.TOTAL_OPENED).value == 3
-        assert output.stats.get(self.PCT_CLOSED).value == 66.67  # rounded to 2 places
+        assert output.stats.get(self.PCT_CLOSED).value == 66  # rounded to 2 places


⬇️ Suggested change

-        assert output.stats.get(self.PCT_CLOSED).value == 66  # rounded to 2 places
+        assert output.stats.get(self.PCT_CLOSED).value == 67  # rounded to nearest whole number


Changed this sounds it reflects the rounding to the nearest whole number

—
Reply to this email directly, view it on GitHub<https://github.com/HHS/simpler-grants-gov/pull/1976#pullrequestreview-2050348150>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BADJYJMIWWOY7WMZFAZZZ5LZBTT7TAVCNFSM6AAAAABHPHBFWOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDANJQGM2DQMJVGA>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-05-13 14:12 UTC, widal001 submitted a review, later dismissed
LGTM! 

I ran `make sprint-reports-with-latest-data ACTION=post-results` and got the following results:

- [Sprint burndown](https://betagrantsgov.slack.com/archives/C06L7JGT9M0/p1715609506850519)
- [Percent complete by deliverable](https://betagrantsgov.slack.com/archives/C06L7JGT9M0/p1715609515827489)

2024-10-15 20:59 UTC, widal001 commented
We'll tackle this in one of the other related issues in #2355

2024-10-15 20:59 UTC, closed without merging